apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-express
  namespace: example
spec:
  replicas: 5
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: ex-example
          image: tpneik/appkube:latest
          ports:
            - name: httpport
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ex-express-service
  namespace: example
spec:
  selector: 
    app: express
  type: NodePort  
  ports:
    - port: 3000
      nodePort: 31313