apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: {{ .Values.appName }}
  type: NodePort  
  ports:
    - port: 3000
      nodePort: {{ .Values.outterPort }}